### ISSUE TITLE
No gateway is registered for schema

### ISSUE THREAD

**Issue by extra2** [viciousviper/DokanCloudFS#20]
Hello!

I can build this solution successfully (there are only warnings) but after that I have this errors all the time:

```
Unhandled Exception: System.Collections.Generic.KeyNotFoundException: No gateway is registered for schema 'box'
   at IgorSoft.DokanCloudFS.CloudDriveFactory.CreateCloudDrive(String schema, String userName, String root, CloudDriveParameters parameters) in C:\***\DokanCloudFS-master\DokanCloudFS\CloudDriveFactory.cs:line 43
   at DokanCloudFS.Mounter.Program.Main(String[] args) in C:\***\DokanCloudFS-master\DokanCloudFS.Mounter\Program.cs:line 60
```

Do I have to modify something? How can I make it works?

Thanks in advance.

**Comment by viciousviper** [comment]
What build configuration are you using? Only *... (NuGet)* and *...(NuGet-Signed)* will pull the required CloudFS Gateways from NuGet during build.
If you use either the *Debug* or *Release* build config you will need to download the [CloudFS](https://github.com/viciousviper/CloudFS) assemblies yourself and place them in a directory matching with the entry in `<mount libPath=...>` in DokanCloudFS.Mounter's `App.config` file. The default location would be the *Library* directory of dhe DokanCloudFS solution.

All this should be documented in *README.md* in sections **Local compilation** and **Usage**. Please let me know if you find this documentation insufficient or misleading.

**Comment by extra2** [comment]
I'm using ...(NuGet). I think the problem was with xcopy (solved now) but this is what I get after I start IgorSoft.DokanCloudFS.Mounter.exe from the command line (as an admin):
```
Unhandled Exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Composition.Hosting.ContainerConfiguration.<WithAssemblies>b__0(Assembly a)
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at IgorSoft.DokanCloudFS.CompositionInitializer.Initialize(String path, String searchPattern) in D:\DokanCloudFS-master\DokanCloudFS\CompositionInitializer.cs:line 97
   at DokanCloudFS.Mounter.Program.Main(String[] args) in D:\DokanCloudFS-master\DokanCloudFS.Mounter\Program.cs:line 51
```

**Comment by viciousviper** [comment]
This would indicate that one of the depencencies of the Box gateway is either missing from the NuGet package (just checked, couldn't find anything wrong, though) or that Visual Studio's automatic package restore mechanism didn't pickup the dependencies for *DokanCloudFS.Gateways* or *DokanCloudFS.Gateways-Signed*.

Could you please try opening the NuGet package manager in Visual Studio and check if there are any pending dependencies for the two *...Gateways* projects?

If this doesn't help at once you could start `IgorSoft.DokanCloudFS.Mounter.exe` from within Visual Studio and look at the `LoaderExceptions` property of the thrown `ReflectionTypeLoadException` in the debugger. This will most likely help to identify the missing dependency.

BTW: What kind of problem with xcopy did you detect and solve?

**Comment by viciousviper** [comment]
Just got another report about the mismatched directory name that causes xcopy to fail.
The latest version [1.0.9](https://github.com/viciousviper/DokanCloudFS/releases/tag/v1.0.9-alpha) should fix this. Please give me a shout if you still encounter problems.

**Comment by viciousviper** [comment]
Closed due to prolonged inactivity.

**Comment by moacirlmjr** [comment]
This problem it's happen to me too (System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information). All the gateways are in the folder Library and the Nugget depedencies in Gateway project don't show missing depedencies. Can you help me in this problem?
